name: Generate Contribution Calendar
on:
  schedule:
    - cron: "0 2 * * *"  # 每天凌晨2点运行
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  contribution-calendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate Full History Calendar
        uses: lowlighter/metrics@latest
        with:
          filename: contribution-calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: sowelswl
          base: ""  # 只显示日历，不显示其他信息
          config_timezone: Asia/Shanghai
          
          # 完整历史贡献日历
          plugin_calendar: yes
          plugin_calendar_limit: 0  # 显示从注册开始的所有年份
          
      - name: Generate Coding Habits Analysis
        uses: lowlighter/metrics@latest
        with:
          filename: coding-habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: sowelswl
          base: ""
          config_timezone: Asia/Shanghai
          
          # 专门的编程习惯分析
          plugin_habits: yes
          plugin_habits_from: 400
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_trim: no  # 显示完整24小时
          plugin_habits_languages_limit: 8
          
      - name: Generate Languages Overview
        uses: lowlighter/metrics@latest
        with:
          filename: languages-overview.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: sowelswl
          base: ""
          config_timezone: Asia/Shanghai
          
          # 专门的语言统计分析
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_threshold: 0.5%
          plugin_languages_other: yes
          plugin_languages_colors: rainbow
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming, markup, data