name: GitHub metrics
on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories, metadata"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stargazers: yes
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_ignored: octonaut
          plugin_achievements_limit: 0
          plugin_languages: yes
          plugin_languages_ignored: html, css, scss, less
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          config_timezone: Asia/Shanghai