name: GitHub metrics
on:
  schedule:
    - cron: "0 */6 * * *"  # 每6小时运行一次
  push:
    branches: [ main ]
  workflow_dispatch:  # 允许手动触发

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal metrics (with GITHUB_TOKEN)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai